### ISSUE TITLE
When creating a folder with ## in its name, characters inserted after are not saved

### ISSUE THREAD

**Issue by ilieandriuta** [xwikisas/application-filemanager#28]
STEPS TO REPRODUCE

1. Right-click on File Manager
2. Create a folder with some letters and ## in its name, in the middle (e.g. Fol##der)
3. Press Enter

EXPECTED RESULTS

The folder is created with the respective name (e.g. Fol##der).

ACTUAL RESULTS

The folder's name is saved truncated, only with the characters it had before the ## (e.g. Fol).

Environment: Windows 10 Pro 64bit, Edge 79, using a local instance of XWiki 11.10.3 on PostgreSQL 12, Tomcat 9.0.27 (tested also on Jetty)

![Folder_name_truncated](https://user-images.githubusercontent.com/32512703/74445490-26fab880-4e7f-11ea-9aa5-9b03ed139f65.jpg)

**Comment by mflorea** [comment]
The issue seems to be that the folder name is parsed for Velocity code.
