### ISSUE TITLE
"See all files" option isn't working

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-filemanager#30]
Steps to reproduce:

1. Add a couple of docs in the File manager
2. Under Recent Files section in the right panel click on See all files

Expected results: All the files uploaded are shown.

Actual results: Nothing happens, only the URL is changed to "FileManager/#?driveNode=%2FallFiles"

Environment: Windows 10, Chrome 80, XWiki 11.10.3, Cloud (11.3.6), XWiki 8.4.5

![SeeAllFiles](https://user-images.githubusercontent.com/40691112/74910118-73d01900-53c2-11ea-9993-e8cce4f5f831.jpg)

**Comment by mflorea** [comment]
@ane-gabriela from the screenshot it looks like you are already viewing the all files, i.e. the All Files node is selected in the tree, so there's nothing to do when clicking on the "See all files" link. Select a different node in the tree and try again. It should select the All Files node as a result. It does for me at least, both on Firefox and Chrome.
