### ISSUE TITLE
Add warning/options when uploading a document with the same name but different case

### ISSUE THREAD

**Issue by iuliabalan** [xwikisas/application-filemanager#34]
Currently, when we upload a document on File Manager if the document's name is only different by lower/upper case a new page is created (since XWiki is case sensitive). 
To not have duplicated documents in FM (that are only different by the name's lower/upper case) it would be nice to have a warning displayed when uploading a document, like  "This document already exists. Do you want to replace it?" and the option to replace the existing document, create a new one, or cancel the upload.

**Comment by iuliabalan** [comment]
Confirmed with @mflorea that the user would have 3 options:
- upload using the original file name (case sensitive)
- upload using the existing attachment name (case insensitive)
- abort the upload

Thanks!

**Comment by oanalavinia** [comment]
Result:

When the similar file is uploaded, a popup is displayed with the upload actions that can be selected:
* upload new file: a new filemanager file is created with the uploaded file name
* replace:
  *  the replace action means that the already existing filemanager file / document is used and this file will be uploaded with that name, creating a new attachment version on the selected page
  *  if multiple similar files are found, the user needs to select which is the replace one

* abort: don't upload the current file (if other file conflicts are present for the uploads in queue, this action is not applied to them and other popups will be shown)

The modal is displayed also if a file with the same name is uploaded

![modal2](https://user-images.githubusercontent.com/22794181/101659447-bc8ab880-3a4e-11eb-94c1-ae4b0119fed0.png)

![modal1](https://user-images.githubusercontent.com/22794181/101656258-2d2fd600-3a4b-11eb-8653-685b12c5a2a4.png)
