### ISSUE TITLE
Thumbnails of images have inconsistent dimensions in 'New file' tab

### ISSUE THREAD

**Issue by oanalavinia** [xwikisas/application-filemanager#42]
Steps to reproduce:
1. Create a folder and go to _New file_ tab
2. Upload a file of different format (like pdf)
3. Upload large images with different dimensions

The result is that the thumbnails of these images could occupy a big portion of the screen, compared to the dimension of a pdf file for example.
Also, if a folder containing multiple of these type of images will be uploaded, it could be hard to scroll though them.

![thumbnails](https://user-images.githubusercontent.com/22794181/106756260-c805f480-6637-11eb-9442-7beafb6a763e.png)

**Comment by mflorea** [comment]
Looks like a use case not covered by #6. @ignatescustefan please take a look.

**Comment by ignatescustefan** [comment]
Here is a screenshot from the application after the fix:
![image](https://user-images.githubusercontent.com/50322733/115190823-44658b00-a0f1-11eb-9ebb-133cfa8a0b50.png)
