### ISSUE TITLE
Make the "Replace the following file" option clearer to the users

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-filemanager#44]
While testing issue #34 I've noticed that the text "Replace the following file" can be a bit misleading for the user. 
![SimilarNames](https://user-images.githubusercontent.com/40691112/107409036-60a6e380-6b14-11eb-82ae-6fe3921fa775.png)

The text implies that the file will be replaced by a new one which includes **content and also the Name/Title**. In this case however, as stated in the comment https://github.com/xwikisas/application-filemanager/issues/34#issuecomment-775906265, only the content is updated, the **Naming remains of the first uploaded file**.

I see 2 options in this case:

1. Rephrase the text, as to make the user understand that the Name/Title will not be changed
2. Add the option to also change the Name if the user wants it (have 2 options to preserve the current page name/title or change it to the new one)

**Comment by oanalavinia** [comment]
The message has been updated to make the option clearer
![updatedMessage](https://user-images.githubusercontent.com/22794181/113146742-b6f0f280-9238-11eb-8c9e-4df9d8aefcab.png)
