### ISSUE TITLE
An attachment with comma symbol in filename can't be opened

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-filemanager#66]
**Environment**: 
XWiki v. 14.10.3
App v. 2.5.5
Browser MS Edge latest

**Step to reproduce**:

1. Install File Manager (Pro)
2. Go to the License tab and obtain a Trial license
3. From the Applications menu, open File Manager
4. Download any PDF sample file from [here](https://freetestdata.com/document-files/pdf/)
5. Rename the downloaded PDF file so it'll have `,` in its filename (for instance, `Free_Test_Data,500KB_PDF.pdf`)
6. Click on the File Manager icon (from a window in step 3) - New File - and select the file from step 5
7. Try to open a newly uploaded PDF file

**Actual Result**
You can't open it, due to the existence of `,` symbol in the filename. The File Manager app will recognize one file as 2 files (`Free_Test_Data` & `500KB_PDF.pdf`)
![image](https://user-images.githubusercontent.com/56109799/224649285-191752b9-f439-48be-a27a-91cb5d28ac49.png)

**Expected Result**
The uploaded PDF file with the name `Free_Test_Data,500KB_PDF.pdf` opened without any issue (as it has or doesn't have `,` in the filename)
![image](https://user-images.githubusercontent.com/56109799/224650308-804240a3-38c8-418f-8761-d02c47244f77.png)

**Current workaround**
Remove from the name `,` or any special symbols that can cause this issue.

**Comment by petrenkonikita112263** [comment]
I think we can close this issue because it doesn't related to File Manager (Pro) directly. The issue is caused by PDF Viewer (Pro) which can't proceed with any pdf attachment with `,` in filename and it is a dependency for File Manager (Pro). Furthermore, the content of this issue was reported on dedicated repository [Macro PDF Viewer (Pro) - The PDF file isn't shown when it contains a comma in the title](https://github.com/xwikisas/macro-pdfviewer/issues/48)

**Comment by oanalavinia** [comment]
The PDFViewer issue was fixed as part of the [2.5.2](https://github.com/xwikisas/macro-pdfviewer/milestone/18?closed=1) release and the dependency was upgraded in https://github.com/xwikisas/application-filemanager/commit/91d5250b300c4bb91db3a313cd91d2438d2e8d17
