### ISSUE TITLE
Two folders having the same name, except one with a trailing space character, are considered having the same content

### ISSUE THREAD

**Issue by mathpce** [xwikisas/application-filemanager#78]
When two folders are named identically, to the exception to a trailing space for one of them, both are displaying the same file content.

Note that there is also a display error (each one of the folder will be displayed two times) but this will be the subject of another issue.

**Versions:**
- XWIKI 15.4
- File Manager (Pro) 2.6

**To reproduce the bug:**
1. open the file manager application
2. create a new folder named "testTrailingSpace" (without the quotes)
3. add a new file in the previously created folder
4. create another new folder named "testTrailingSpace " (note the presence of the trailing space)
5. open the second folder and see that the file added in the first folder is displayed here too

Note: the name of the folder needs to be one never used before (even for a deleted folder) because the page reference wouldn't be the same as the title (you would have "testTrailingSpace1" and "testTrailingSpace " for instance ).

**Comment by ChiuchiuSorin** [comment]
Fixed with https://github.com/xwikisas/application-filemanager/pull/98.
