### ISSUE TITLE
Two folders having the same name, except one with a trailing space character, are displayed two times

### ISSUE THREAD

**Issue by mathpce** [xwikisas/application-filemanager#79]
When two folders are named identically, to the exception to a trailing space for one of them, both of them are displayed two times.

Note that their content is also displayed as being the same, see #78.

This is a problem not limited to the File Manager app. I've seen it also in the Navigation Panel and in the Breadcrumb, but the issue was not reported here.
See this [forum thread](https://forum.xwiki.org/t/rename-page-with-accidental-trailing-whitespace/8553) and these related issues: [XWIKI-11617](https://jira.xwiki.org/browse/XWIKI-11617) and [XWIKI-14354](https://jira.xwiki.org/browse/XWIKI-14354)

### Versions:
-  XWIKI 15.4
-  File Manager (Pro) 2.6

### To reproduce the bug:
1. open the file manager application
2. create a new folder named "testTrailingSpace" (without the quotes)
3. create another new folder named "testTrailingSpace " (note the presence of the trailing space)
4. see that each one is displayed two times

Note: the name of the folder needs to be one never used before (even for a deleted folder) because the page reference wouldn't be the same as the title (you would have "testTrailingSpace1" and "testTrailingSpace " for instance ).

**Comment by ChiuchiuSorin** [comment]
Fixed with https://github.com/xwikisas/application-filemanager/pull/98.
