### ISSUE TITLE
Can't access a folder that was copied in another folder

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-filemanager#80]
Steps to reproduce:

1. Access the File Manager
2. Right click and create 2 new folders
3. Right click on one of the folders
4. Select Copy
5. Click on the other folder
6. Right click and select Paste Into Folder
7. Click on the arrow to see both folders

Expected results: The folder was copied to the new location and both folders can be seen and accessed.

Actual results: The copied folder doesn't appear, an error appears in the browser and in the wiki console.

![ResultAfterPaste](https://github.com/xwikisas/application-filemanager/assets/40691112/bcf0602a-e705-46cd-9943-2bdcb63a9974)

In the wiki console:
`2023-09-22 14:15:17,930 [qtp382750013-26 - http://localhost:8080/xwiki/bin/view/FileManager/] ERROR o.a.v.rendering                - Left side ($paths.length) of comparison operation has null value at xwiki:FileManagerCode.RecentFilesPanel[line 5, column 21]`

Environment: Windows 11, Chrome 117, XWiki 14.10.5, File Manager Application (Pro) 2.6

**Comment by ane-gabriela** [comment]
Same issue when cutting and pasting a folder in another one.

**Comment by petrenkonikita112263** [comment]
The workaround for this issue (I've reproduced it also on 15.9 XWiki) - right click on the desired folder and select "Open in a new tab", then in new window a copied/pasted folder will be visible and accessible,
