### ISSUE TITLE
User can not download an archive of subfolder with or without files

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-filemanager#85]
**Environment**: XWiki 15.9, latest version of web-browser clients MS Edge, Google Chrome, Firefox. OS - W10.

**Prerequisites**:

- XWiki instance 15.x.
- Latest version of File Manager (Pro). 
- Trial license

**Step to reproduce:**

1. Create a similar folder structure that on the screenshot below (naming doesn't matter)

![image](https://github.com/xwikisas/application-filemanager/assets/56109799/37cd72de-9982-4df1-bec0-1503cc43a993)

2. Upload any file to at least one subfolder, for instance, XWiki folder
3. Right-click on XWiki folder → Download

**Actual result**:
You will notice that zip archive with name XWiki.zip was formed, and its size 0 bytes, but you'll automatically forward into an empty page with URL [http://localhost/xwiki/bin/get/FileManager/Download-Admin-XWiki](http://localhost/xwiki/bin/get/FileManager/Download-Admin-XWiki). 
Press CTRL + ← if you're on Windows or similar command on Linux in order to return to previous page in tab.
In console or dev tools, there's no error.

**Expected result**:
After zip archive is finished, it will automatically be downloaded by the web-browser client. As it happens with the root folder.

GIF of recorded action from Firefox

![firefox_HEJ4wB4MOv](https://github.com/xwikisas/application-filemanager/assets/56109799/d3552d00-b709-4e94-99c7-bba2b6a8cd6f)

**Comment by petrenkonikita112263** [comment]
Furthermore, the created page _but not downloaded_ zip can be seen and reachable from breadcrumb menu, by navigating to the page

![image](https://github.com/xwikisas/application-filemanager/assets/56109799/3c4fbb99-ca20-44a2-a8a9-1d9bc6454e7f)


![image](https://github.com/xwikisas/application-filemanager/assets/56109799/fcb1ed86-eb71-4dd4-8fc6-2bec5d5fa27f)

**Comment by ChiuchiuSorin** [comment]
I tested the issue on XWiki version 14.10 and 15.9 and it does not reproduce.

**Comment by petrenkonikita112263** [comment]
@ChiuchiuSorin thanks for confirmation on issue status on 14.10. But currently minimal parent version is still 13.10. I'll check on my end on 14.10 in following days. But I propose to leave it open until parent won't be updated to 14.10.

**Comment by petrenkonikita112263** [comment]
Indeed, I can't reproduce it anymore on FM (Pro) 2.7 on 15.9 XWiki
