### ISSUE TITLE
Added attachment to uploaded file replaces it and duplicates itself on FileManager WebHome page

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-filemanager#90]
_Note_: firstly issue was reproduced on old version File Manager (Pro) 2.4 and XWiki platform 10.11.9

**Prerequisites**:

- XWiki instance 13.10.
- Latest version of File Manager (Pro).
- Trial license

**Step to reproduce:**

1. Navigate into FileManager.WebHome page
2. Create a folder with dummy name
3. Upload file into this folder
4. Go to a page with an uploaded file, scroll down or select Attachment section from More actions menu
5. Upload an attachment _different name_ and _different type_
6. Refresh the FileManager.WebHome page and check lately created folder

Steps are shown in below GIF
![firefox_t2w95eJdZl](https://github.com/xwikisas/application-filemanager/assets/56109799/67b7975c-9ca3-4f8e-841a-9543fa4411a5)

**Actual result**:
Firstly, you'll not see your file from step 3, instead of it 2 duplications will be present  - attachment from step 5, however both links will point to file from step 3 http://localhost:8080/xwiki/bin/view/FileManager/test.txt. Second if you click on this link you will not see content of file from step 3 - content of attachment from step 5 

![image](https://github.com/xwikisas/application-filemanager/assets/56109799/b26aec87-27c7-4d22-807e-89c564bb2667)

If you decide to select one of them, File Manager will automatically select a duplicate. 
![firefox_yPVcIlhpSQ](https://github.com/xwikisas/application-filemanager/assets/56109799/a684d579-9d51-46f4-a104-cbd92eb1d7f5)

In addition, if you open your folder in new tab - you will see only one attachment from step 5.
![image](https://github.com/xwikisas/application-filemanager/assets/56109799/60a2cf44-0dae-4fef-961b-84632c8a1441)

**Expected result**:
No duplication in FileManager.WebHome and uploaded attachment doesn't replace visually uploaded file.

**Comment by mflorea** [comment]
@petrenkonikita112263 you need to explain your use case. Why do you need to add an attachment to a File Manager page? What are you trying to achieve? Normally you shouldn't add attachments to the File Manager's pages. You should interact with the File Manager pages through the File Manager UI. I agree that the code could be bulletproofed to ignore the extra attachments, but that's a minor issue.

**Comment by ChiuchiuSorin** [comment]
No longer needed after implementing https://github.com/xwikisas/application-filemanager/issues/92.
