### ISSUE TITLE
Disable attachment section for uploaded file page and its siblings

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-filemanager#92]
This might be an alternative solution to issue #90.

OMV, the primary idea of File Manager - organizing and storing any file in a folder on XWiki. These files can be observed by users depending on rights management. And any further upload process should only be performed from File Manager and not attachment sections.

**Comment by ChiuchiuSorin** [comment]
Issue completed in PR https://github.com/xwikisas/application-filemanager/pull/95
